Repository UMC5th-bias/MoeMoe-Server, pull requests merged in 2024-08, with the labels that each got.

#117 [FIX/#116] 일반 회원가입시 ATK, RTK 함께 반환하도록 수정 & JwtAuthenticationFilter 클래스 주석처리 해제
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
  src/main/java/com/favoriteplace/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/favoriteplace/global/security/provider/JwtTokenProvider.java
Labels: :bug: bug, 로그인/회원가입

#122 [REFACTOR #115] STOMP를 이용한 성지순례 장소 인증 기능 리팩토링
  build.gradle
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/controller/MemberController.java
  src/main/java/com/favoriteplace/app/controller/PilgrimageSocketController.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageSocketDto.java
  src/main/java/com/favoriteplace/app/service/MyPageQueryService.java
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
  src/main/java/com/favoriteplace/app/service/WebSocketService.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
  src/main/java/com/favoriteplace/global/security/config/RedisConfig.java
  src/main/java/com/favoriteplace/global/security/provider/JwtTokenProvider.java
  src/main/java/com/favoriteplace/global/util/SchedulerService.java
  src/main/java/com/favoriteplace/global/util/SecurityUtil.java
  src/main/java/com/favoriteplace/global/websocket/JwtChannelInterceptor.java
  src/main/java/com/favoriteplace/global/websocket/RedisService.java
  src/main/java/com/favoriteplace/global/websocket/WebSocketConfig.java
Labels: :recycle: refactor, 성지순례

#127 [DEPLOY] 배포 스크립트 파일명 수정 nun_new_was.sh > run_new_was.sh
  scripts/run_new_was.sh
Labels: 🔆 deploy

#129 [DEPLOY] main <- develop 병합
  scripts/run_new_was.sh
Labels: 🔆 deploy

#130 [DEPLOY #124] healthcheck controller 수정
  src/main/java/com/favoriteplace/app/controller/HealthCheckController.java
Labels: 🔆 deploy

#131 [DEPLOY #124] healthCheckController 수정
  src/main/java/com/favoriteplace/app/controller/HealthCheckController.java
Labels: 🔆 deploy

#132 [DEPLOY] main <- develop 병합
  src/main/java/com/favoriteplace/app/controller/HealthCheckController.java
Labels: 🔆 deploy

#134 [REFACTOR #115] 성지순례 Redis 충돌 해결 및 버튼 상태 업데이터 메서드 완성
  build.gradle
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/controller/PilgrimageSocketController.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageSocketDto.java
  src/main/java/com/favoriteplace/app/repository/GuestBookRepository.java
  src/main/java/com/favoriteplace/app/repository/VisitedPilgrimageRepository.java
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
  src/main/java/com/favoriteplace/app/service/WebSocketService.java
  src/main/java/com/favoriteplace/global/security/config/JacksonConfig.java
  src/main/java/com/favoriteplace/global/security/config/RedisConfig.java
  src/main/java/com/favoriteplace/global/websocket/JwtChannelInterceptor.java
  src/main/java/com/favoriteplace/global/websocket/RedisService.java
Labels: :bug: bug, :recycle: refactor

#135 [FEAT] 카카오 회원가입 구현
  src/main/java/com/favoriteplace/app/controller/MemberController.java
  src/main/java/com/favoriteplace/app/domain/Member.java
  src/main/java/com/favoriteplace/app/dto/member/KaKaoSignUpRequestDto.java
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/global/security/config/FeignClientConfig.java
Labels: :sparkles: feature, 로그인/회원가입

#136 [DEPLOY] main <- develop 병합
  build.gradle
  src/main/java/com/favoriteplace/app/controller/MemberController.java
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/controller/PilgrimageSocketController.java
  src/main/java/com/favoriteplace/app/domain/Member.java
  src/main/java/com/favoriteplace/app/dto/member/KaKaoSignUpRequestDto.java
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageSocketDto.java
  src/main/java/com/favoriteplace/app/repository/GuestBookRepository.java
  src/main/java/com/favoriteplace/app/repository/VisitedPilgrimageRepository.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
  src/main/java/com/favoriteplace/app/service/WebSocketService.java
  src/main/java/com/favoriteplace/global/security/config/FeignClientConfig.java
  src/main/java/com/favoriteplace/global/security/config/JacksonConfig.java
  src/main/java/com/favoriteplace/global/security/config/RedisConfig.java
  src/main/java/com/favoriteplace/global/websocket/JwtChannelInterceptor.java
  src/main/java/com/favoriteplace/global/websocket/RedisService.java
Labels: 🔆 deploy

#139 [FIX #121] 카카오 회원가입 AuthKakaoLoginDto json 매핑 못하는 문제 해결
  .github/workflows/develop.yml
  .github/workflows/main.yml
  src/main/java/com/favoriteplace/app/dto/member/AuthKakaoLoginDto.java
Labels: 🔆 deploy
