Repository UMC5th-bias/MoeMoe-Server, pull requests merged in 2024-09, with the labels that each got.

#133 [FEAT #114] FCM
  build.gradle
  src/main/java/com/favoriteplace/app/controller/FCMNotificationController.java
  src/main/java/com/favoriteplace/app/controller/GuestBookCommentController.java
  src/main/java/com/favoriteplace/app/controller/MyPageController.java
  src/main/java/com/favoriteplace/app/controller/NotificationController.java
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/controller/PostCommentController.java
  src/main/java/com/favoriteplace/app/converter/FcmConverter.java
  src/main/java/com/favoriteplace/app/converter/NotificationConverter.java
  src/main/java/com/favoriteplace/app/domain/Member.java
  src/main/java/com/favoriteplace/app/domain/Notification.java
  src/main/java/com/favoriteplace/app/dto/MyPageDto.java
  src/main/java/com/favoriteplace/app/dto/NotificationResponseDto.java
  src/main/java/com/favoriteplace/app/dto/community/PostResponseDto.java
  src/main/java/com/favoriteplace/app/dto/fcm/FcmMessage.java
  src/main/java/com/favoriteplace/app/dto/fcm/FcmNotificationRequest.java
  src/main/java/com/favoriteplace/app/repository/LikedRallyRepository.java
  src/main/java/com/favoriteplace/app/repository/NotificationRepository.java
  src/main/java/com/favoriteplace/app/service/MyPageCommandService.java
  src/main/java/com/favoriteplace/app/service/NotificationService.java
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
  src/main/java/com/favoriteplace/app/service/community/CommentCommandService.java
  src/main/java/com/favoriteplace/app/service/fcm/FCMNotificationService.java
  src/main/java/com/favoriteplace/app/service/fcm/dto/PostTokenCond.java
  src/main/java/com/favoriteplace/app/service/fcm/enums/TokenMessage.java
  src/main/java/com/favoriteplace/app/service/fcm/enums/TotalTopicMessage.java
  src/main/java/com/favoriteplace/global/config/FcmConfig.java
  src/main/java/com/favoriteplace/global/exception/ErrorCode.java
  src/main/java/com/favoriteplace/global/security/config/SecurityConfig.java
  src/main/java/com/favoriteplace/global/security/filter/ExceptionHandlerFilter.java
  src/main/java/com/favoriteplace/global/security/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/favoriteplace/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/favoriteplace/global/security/filter/LoginFilter.java
Labels: :sparkles: feature

#140 [FIX #138] STOMP connect 이벤트 버그 해결
  src/main/java/com/favoriteplace/app/controller/PilgrimageSocketController.java
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
  src/main/java/com/favoriteplace/global/websocket/RedisService.java
Labels: :bug: bug

#143 [FEAT] AWS S3 이미지 업로드 로직 구현
  Group 483718@2x.png
  build.gradle
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/global/config/AsyncConfig.java
  src/main/java/com/favoriteplace/global/config/S3Config.java
  src/main/java/com/favoriteplace/global/exception/ExceptionHandlerAdvice.java
  src/main/java/com/favoriteplace/global/s3Image/AmazonS3ImageManager.java
Labels: :sparkles: feature

#146 [FIX #145] SockJS 설정 제거
  src/main/java/com/favoriteplace/global/websocket/WebSocketConfig.java
Labels: :bug: bug, 성지순례

#148 [DEPLOY] main <- develop 병합
  Group 483718@2x.png
  README.md
  build.gradle
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/global/config/AsyncConfig.java
  src/main/java/com/favoriteplace/global/config/S3Config.java
  src/main/java/com/favoriteplace/global/exception/ExceptionHandlerAdvice.java
  src/main/java/com/favoriteplace/global/s3Image/AmazonS3ImageManager.java
  src/main/java/com/favoriteplace/global/websocket/WebSocketConfig.java
Labels: 🔆 deploy

#150 [FIX #149] 자유게시글, 성지순례 인증글 이미지 업로드 로직 수정
  src/main/java/com/favoriteplace/app/controller/PostController.java
  src/main/java/com/favoriteplace/app/domain/community/GuestBook.java
  src/main/java/com/favoriteplace/app/domain/community/Post.java
  src/main/java/com/favoriteplace/app/domain/enums/ItemType.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
  src/main/java/com/favoriteplace/app/service/community/PostCommandService.java
  src/main/java/com/favoriteplace/global/s3Image/AmazonS3ImageManager.java
Labels: 🛠 fix

#151 [FIX #144] 이미지 업로드 로직 수정
  src/main/java/com/favoriteplace/HealthCheckController.java
  src/main/java/com/favoriteplace/app/controller/HealthCheckController.java
  src/main/java/com/favoriteplace/app/controller/MemberController.java
  src/main/java/com/favoriteplace/app/dto/member/KaKaoSignUpRequestDto.java
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/global/s3Image/AmazonS3ImageManager.java
Labels: 로그인/회원가입, 🛠 fix

#152 [DEPLOY] main <- develop 병합
  src/main/java/com/favoriteplace/HealthCheckController.java
  src/main/java/com/favoriteplace/app/controller/HealthCheckController.java
  src/main/java/com/favoriteplace/app/controller/MemberController.java
  src/main/java/com/favoriteplace/app/controller/PostController.java
  src/main/java/com/favoriteplace/app/domain/community/GuestBook.java
  src/main/java/com/favoriteplace/app/domain/community/Post.java
  src/main/java/com/favoriteplace/app/domain/enums/ItemType.java
  src/main/java/com/favoriteplace/app/dto/member/KaKaoSignUpRequestDto.java
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
  src/main/java/com/favoriteplace/app/service/community/PostCommandService.java
  src/main/java/com/favoriteplace/global/s3Image/AmazonS3ImageManager.java
Labels: 🔆 deploy

#154 [Refactor #153] 자유게시판, 성지순례 인증글 response DTO, status 수정
  src/main/java/com/favoriteplace/app/controller/GuestBookCommentController.java
  src/main/java/com/favoriteplace/app/controller/GuestBookController.java
  src/main/java/com/favoriteplace/app/controller/MyPageController.java
  src/main/java/com/favoriteplace/app/controller/NotificationController.java
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/controller/PostCommentController.java
  src/main/java/com/favoriteplace/app/controller/PostController.java
  src/main/java/com/favoriteplace/app/domain/community/GuestBook.java
  src/main/java/com/favoriteplace/app/dto/community/PostResponseDto.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
  src/main/java/com/favoriteplace/app/service/community/LikedPostService.java
Labels: :recycle: refactor
