Repository UMC5th-bias/MoeMoe-Server, pull requests merged in 2024-01, with the labels that each got.

#7 [Feat/#3] 일반 로그인 및 회원가입 API 구현
  build.gradle
  src/main/java/com/favoriteplace/app/controller/HomeController.java
  src/main/java/com/favoriteplace/app/controller/MemberController.java
  src/main/java/com/favoriteplace/app/domain/Member.java
  src/main/java/com/favoriteplace/app/domain/item/AcquiredItem.java
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/repository/MemberRepository.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/global/exception/ErrorCode.java
  src/main/java/com/favoriteplace/global/security/CustomUserDetails.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
  src/main/java/com/favoriteplace/global/security/Filter/LoginFilter.java
  src/main/java/com/favoriteplace/global/security/config/SecurityConfig.java
  src/main/java/com/favoriteplace/global/security/handler/CustomAuthenticationFailHandler.java
  src/main/java/com/favoriteplace/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/favoriteplace/global/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/favoriteplace/global/security/provider/JwtTokenProvider.java
  src/main/java/com/favoriteplace/global/security/service/CustomUserDetailsService.java
  src/main/java/com/favoriteplace/global/util/SecurityUtil.java
  src/main/resources/application.yml
Labels: :sparkles: feature, 로그인/회원가입

#13 [FEAT #12] jwt 헤더 검증 절차 수정, 성지순례 조회 dto 추가
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/converter/RallyConverter.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageDto.java
  src/main/java/com/favoriteplace/app/dto/travel/RallyDto.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
  src/main/java/com/favoriteplace/global/util/SecurityUtil.java
Labels: :bug: bug, :sparkles: feature

#16 [FEAT #8] 이메일 인증코드 요청 및 확인 API 구현
  build.gradle
  src/main/java/com/favoriteplace/app/controller/MemberController.java
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/service/MailSendService.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/global/exception/ErrorCode.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
  src/main/java/com/favoriteplace/global/security/Filter/LoginFilter.java
  src/main/java/com/favoriteplace/global/security/config/EmailConfig.java
  src/main/java/com/favoriteplace/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/favoriteplace/global/util/RedisUtil.java
  src/main/java/com/favoriteplace/global/util/SecurityUtil.java
Labels: :sparkles: feature, 로그인/회원가입

#14 [FIX #12] 성지순례 카테고리 별 조회 API 개발
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/converter/PilgrimageConverter.java
  src/main/java/com/favoriteplace/app/converter/RallyConverter.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageDto.java
  src/main/java/com/favoriteplace/app/dto/travel/RallyDto.java
  src/main/java/com/favoriteplace/app/repository/AddressRepository.java
  src/main/java/com/favoriteplace/app/repository/GuestBookRepository.java
  src/main/java/com/favoriteplace/app/repository/ImageRepository.java
  src/main/java/com/favoriteplace/app/repository/LikedRallyRepository.java
  src/main/java/com/favoriteplace/app/repository/RallyRepository.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor, 성지순례

#21 [FEAT #17] 이메일 중복 여부 확인 API 구현
  src/main/java/com/favoriteplace/app/controller/MemberController.java
  src/main/java/com/favoriteplace/app/dto/member/Empty.java
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/service/MailSendService.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
Labels: :sparkles: feature

#23 [FEAT #19] 커뮤니티-자유게시판 : 이미지 처리, 게시글 추가&삭제&좋아요, 댓글 작성
  .gitignore
  build.gradle
  src/main/java/com/favoriteplace/app/controller/PostController.java
  src/main/java/com/favoriteplace/app/domain/Image.java
  src/main/java/com/favoriteplace/app/domain/community/Post.java
  src/main/java/com/favoriteplace/app/dto/community/CommentRequestDto.java
  src/main/java/com/favoriteplace/app/dto/community/PostRequestDto.java
  src/main/java/com/favoriteplace/app/dto/community/PostResponseDto.java
  src/main/java/com/favoriteplace/app/repository/LikedPostRepository.java
  src/main/java/com/favoriteplace/app/service/CommentService.java
  src/main/java/com/favoriteplace/app/service/LikedPostService.java
  src/main/java/com/favoriteplace/app/service/PostService.java
  src/main/java/com/favoriteplace/global/gcpImage/GoogleCloudStorageConfig.java
  src/main/java/com/favoriteplace/global/gcpImage/UploadImage.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
Labels: :sparkles: feature, 커뮤니티

#24 [FEAT] 성지순례 조회 API 개발 완료
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/converter/PilgrimageConverter.java
  src/main/java/com/favoriteplace/app/converter/RallyConverter.java
  src/main/java/com/favoriteplace/app/repository/LikedRallyRepository.java
  src/main/java/com/favoriteplace/app/repository/PilgrimageRepository.java
  src/main/java/com/favoriteplace/app/repository/RallyRepository.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
  src/main/java/com/favoriteplace/global/exception/ErrorCode.java
Labels: :sparkles: feature, 성지순례

#27 [FEAT #22] 상점 - 한정판매 아이템 리스트 API 구현 (회원/비회원)
  .gitignore
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/controller/ShopController.java
  src/main/java/com/favoriteplace/app/converter/ShopConverter.java
  src/main/java/com/favoriteplace/app/domain/Member.java
  src/main/java/com/favoriteplace/app/domain/enums/ItemCategory.java
  src/main/java/com/favoriteplace/app/domain/item/Item.java
  src/main/java/com/favoriteplace/app/dto/item/ItemDto.java
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/repository/ItemRepository.java
  src/main/java/com/favoriteplace/app/service/ShopService.java
  src/main/java/com/favoriteplace/global/util/SecurityUtil.java
Labels: :sparkles: feature, 상점

#32 [FEAT] 마이페이지 내 정보 조회 API 개발
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/controller/MyPageController.java
  src/main/java/com/favoriteplace/app/converter/MyPageConverter.java
  src/main/java/com/favoriteplace/app/dto/MyPageDto.java
  src/main/java/com/favoriteplace/app/repository/AcquiredItemRepository.java
  src/main/java/com/favoriteplace/app/repository/BlockRepository.java
  src/main/java/com/favoriteplace/app/service/MyPageQueryService.java
  src/main/java/com/favoriteplace/global/exception/ErrorCode.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
Labels: :sparkles: feature, 마이페이지

#34 [Feat #26] 커뮤니티 - 성지순례 : Get Method, 게시글 추가&수정 api 수정
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/controller/GuestBookController.java
  src/main/java/com/favoriteplace/app/controller/PostController.java
  src/main/java/com/favoriteplace/app/controller/TrendingPostController.java
  src/main/java/com/favoriteplace/app/converter/CommentConverter.java
  src/main/java/com/favoriteplace/app/converter/GuestBookConverter.java
  src/main/java/com/favoriteplace/app/converter/PostConverter.java
  src/main/java/com/favoriteplace/app/domain/community/GuestBook.java
  src/main/java/com/favoriteplace/app/domain/community/Post.java
  src/main/java/com/favoriteplace/app/dto/community/CommentResponseDto.java
  src/main/java/com/favoriteplace/app/dto/community/GuestBookResponseDto.java
  src/main/java/com/favoriteplace/app/dto/community/PostRequestDto.java
  src/main/java/com/favoriteplace/app/dto/community/PostResponseDto.java
  src/main/java/com/favoriteplace/app/repository/CommentRepository.java
  src/main/java/com/favoriteplace/app/repository/GuestBookRepository.java
  src/main/java/com/favoriteplace/app/repository/ImageRepository.java
  src/main/java/com/favoriteplace/app/repository/LikedPostRepository.java
  src/main/java/com/favoriteplace/app/service/CommentService.java
  src/main/java/com/favoriteplace/app/service/CountComments.java
  src/main/java/com/favoriteplace/app/service/GuestBookService.java
  src/main/java/com/favoriteplace/app/service/LikedPostService.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
  src/main/java/com/favoriteplace/app/service/PostCommandService.java
  src/main/java/com/favoriteplace/app/service/PostQueryService.java
  src/main/java/com/favoriteplace/app/service/RallyService.java
  src/main/java/com/favoriteplace/app/service/sortStrategy/SortGuestBookByLatestStrategy.java
  src/main/java/com/favoriteplace/app/service/sortStrategy/SortGuestBookByLikedStrategy.java
  src/main/java/com/favoriteplace/app/service/sortStrategy/SortPostByLatestStrategy.java
  src/main/java/com/favoriteplace/app/service/sortStrategy/SortPostByLikedStrategy.java
  src/main/java/com/favoriteplace/app/service/sortStrategy/SortStrategy.java
  src/main/java/com/favoriteplace/app/service/strategy/SortStrategy.java
  src/main/java/com/favoriteplace/global/gcpImage/ConvertUuidToUrl.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
Labels: :sparkles: feature, :recycle: refactor, 커뮤니티

#35 [FEAT #30] - 상점_신상품 목록 조회 API 구현
  src/main/java/com/favoriteplace/app/controller/ShopController.java
  src/main/java/com/favoriteplace/app/converter/ShopConverter.java
  src/main/java/com/favoriteplace/app/dto/item/ItemDto.java
  src/main/java/com/favoriteplace/app/repository/ItemRepository.java
  src/main/java/com/favoriteplace/app/service/ShopService.java
Labels: :sparkles: feature, 상점

#40 [FEAT #39] - 상점 상세페이지 API 구현
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/controller/ShopController.java
  src/main/java/com/favoriteplace/app/domain/item/Item.java
  src/main/java/com/favoriteplace/app/dto/item/ItemDto.java
  src/main/java/com/favoriteplace/app/repository/AcquiredItemRepository.java
  src/main/java/com/favoriteplace/app/repository/ItemRepository.java
  src/main/java/com/favoriteplace/app/service/ShopService.java
  src/main/java/com/favoriteplace/global/exception/ErrorCode.java
  src/main/java/com/favoriteplace/global/util/SecurityUtil.java
Labels: :sparkles: feature, 상점

#41 [FEAT] 성지순례 일부 기능 및 임시 더미데이터 추가
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/converter/CommonConverter.java
  src/main/java/com/favoriteplace/app/converter/PilgrimageConverter.java
  src/main/java/com/favoriteplace/app/converter/PointHistoryConverter.java
  src/main/java/com/favoriteplace/app/domain/Member.java
  src/main/java/com/favoriteplace/app/domain/enums/RallyVersion.java
  src/main/java/com/favoriteplace/app/domain/item/PointHistory.java
  src/main/java/com/favoriteplace/app/domain/travel/CompleteRally.java
  src/main/java/com/favoriteplace/app/domain/travel/Rally.java
  src/main/java/com/favoriteplace/app/dto/CommonResponseDto.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageDto.java
  src/main/java/com/favoriteplace/app/repository/CompleteRallyRepository.java
  src/main/java/com/favoriteplace/app/repository/PointHistoryRepository.java
  src/main/java/com/favoriteplace/app/repository/VisitedPilgrimageRepository.java
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
  src/main/java/com/favoriteplace/global/exception/ErrorCode.java
Labels: :bug: bug, :sparkles: feature, 성지순례

#44 [FIX #42] 일반 회원가입 - 사용자 프로필 이미지 + 새싹회원 칭호 저장
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/controller/MemberController.java
  src/main/java/com/favoriteplace/app/domain/Member.java
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/repository/ItemRepository.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
Labels: :bug: bug, 상점
