Repository UMC5th-bias/MoeMoe-Server, pull requests merged in 2024-02, with the labels that each got.

#52 [FEAT #49] 댓글(자유게시판&성지순례) 수정&삭제
  build.gradle
  src/main/java/com/favoriteplace/app/controller/GuestBookCommentController.java
  src/main/java/com/favoriteplace/app/controller/GuestBookController.java
  src/main/java/com/favoriteplace/app/controller/PostCommentController.java
  src/main/java/com/favoriteplace/app/controller/PostController.java
  src/main/java/com/favoriteplace/app/controller/TrendingPostController.java
  src/main/java/com/favoriteplace/app/domain/community/Comment.java
  src/main/java/com/favoriteplace/app/service/Empty.java
  src/main/java/com/favoriteplace/app/service/community/CommentCommandService.java
  src/main/java/com/favoriteplace/app/service/community/CommentQueryService.java
  src/main/java/com/favoriteplace/app/service/community/CountCommentsService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookQueryService.java
  src/main/java/com/favoriteplace/app/service/community/LikedPostService.java
  src/main/java/com/favoriteplace/app/service/community/PostCommandService.java
  src/main/java/com/favoriteplace/app/service/community/PostQueryService.java
  src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortGuestBookByLatestStrategy.java
  src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortGuestBookByLikedStrategy.java
  src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortPostByLatestStrategy.java
  src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortPostByLikedStrategy.java
  src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortStrategy.java
  src/main/java/com/favoriteplace/global/exception/ErrorCode.java
  src/main/java/com/favoriteplace/global/gcpImage/GoogleCloudStorageConfig.java
  src/main/java/com/favoriteplace/global/gcpImage/UploadImage.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
Labels: :sparkles: feature, 커뮤니티

#51 [FEAT] 성지순례 인증글 작성 api 개발
  src/main/java/com/favoriteplace/app/controller/GuestBookController.java
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/domain/community/HashTag.java
  src/main/java/com/favoriteplace/app/dto/community/GuestBookRequestDto.java
  src/main/java/com/favoriteplace/app/repository/VisitedPilgrimageRepository.java
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
  src/main/java/com/favoriteplace/global/exception/ErrorCode.java
Labels: :bug: bug, :sparkles: feature, 성지순례

#56 [FIX #55] 충돌 해결
  src/main/java/com/favoriteplace/app/controller/GuestBookController.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
Labels: :bug: bug

#58 [FEAT #54] 상품 구매 API 구현
  .gitignore
  scripts/start.sh
  src/main/java/com/favoriteplace/FavoritePlaceApplication.java
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/controller/ShopController.java
  src/main/java/com/favoriteplace/app/domain/enums/ItemCategory.java
  src/main/java/com/favoriteplace/app/dto/item/ItemDto.java
  src/main/java/com/favoriteplace/app/repository/ItemRepository.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/app/service/ShopService.java
  src/main/java/com/favoriteplace/global/gcpImage/ConvertUuidToUrl.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
  src/main/java/com/favoriteplace/global/util/SchedulerService.java
Labels: :bug: bug, :sparkles: feature, 상점

#59 [FIX] 포인트 지급 로직 수정 및 사용자 착용 아이템 null 예외처리
  .gitignore
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/converter/MyPageConverter.java
  src/main/java/com/favoriteplace/app/converter/PilgrimageConverter.java
  src/main/java/com/favoriteplace/app/domain/community/GuestBook.java
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
Labels: :bug: bug, 성지순례, 마이페이지

#60 [FEAT #53] 배포 api 수정 및 이미지 버킷 교체
  src/main/java/com/favoriteplace/app/controller/GuestBookController.java
  src/main/java/com/favoriteplace/app/converter/CommentConverter.java
  src/main/java/com/favoriteplace/app/converter/TrendingPostConverter.java
  src/main/java/com/favoriteplace/app/dto/UserInfoResponseDto.java
  src/main/java/com/favoriteplace/app/dto/community/TrendingPostResponseDto.java
  src/main/java/com/favoriteplace/app/service/TotalPostService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
Labels: :recycle: refactor, 커뮤니티

#63 [FEAT #62] 성지순례 검색 api 구현(like 사용)
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/converter/RallyConverter.java
  src/main/java/com/favoriteplace/app/dto/travel/RallyDto.java
  src/main/java/com/favoriteplace/app/repository/AddressRepository.java
  src/main/java/com/favoriteplace/app/repository/RallyRepository.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
Labels: :sparkles: feature, 성지순례

#64 [FEAT #61] 커뮤니티(자유게시판&성지순례인증글) 검색 api 구현, 이미지 병렬 처리
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/controller/GuestBookController.java
  src/main/java/com/favoriteplace/app/controller/PostController.java
  src/main/java/com/favoriteplace/app/converter/CommentConverter.java
  src/main/java/com/favoriteplace/app/converter/GuestBookConverter.java
  src/main/java/com/favoriteplace/app/domain/community/Post.java
  src/main/java/com/favoriteplace/app/dto/community/GuestBookResponseDto.java
  src/main/java/com/favoriteplace/app/repository/Empty.java
  src/main/java/com/favoriteplace/app/repository/GuestBookRepository.java
  src/main/java/com/favoriteplace/app/repository/PostRepository.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookQueryService.java
  src/main/java/com/favoriteplace/app/service/community/PostCommandService.java
  src/main/java/com/favoriteplace/app/service/community/PostQueryService.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchGuestBookByContent.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchGuestBookByNickname.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchGuestBookByTitle.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchPostByContent.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchPostByNickname.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchPostByTitle.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchStrategy.java
  src/main/java/com/favoriteplace/global/exception/ErrorCode.java
  src/main/java/com/favoriteplace/global/exception/ExceptionHandlerAdvice.java
  src/main/java/com/favoriteplace/global/gcpImage/UploadImage.java
Labels: :sparkles: feature, :recycle: refactor, 커뮤니티

#68 [FEAT #66] 상점 - 아이템 구매시 로직 추가 및 스케줄링 수정
  src/main/java/com/favoriteplace/app/domain/Member.java
  src/main/java/com/favoriteplace/app/service/ShopService.java
  src/main/java/com/favoriteplace/global/util/SchedulerService.java
Labels: :bug: bug, :sparkles: feature, 상점

#69 [FIX] 성지순례 api 수정 및 아이템 착용 api 개발
  src/main/java/com/favoriteplace/app/controller/MyPageController.java
  src/main/java/com/favoriteplace/app/converter/PilgrimageConverter.java
  src/main/java/com/favoriteplace/app/domain/Member.java
  src/main/java/com/favoriteplace/app/domain/community/GuestBook.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageDto.java
  src/main/java/com/favoriteplace/app/service/MyPageCommandService.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
  src/main/java/com/favoriteplace/global/exception/ErrorCode.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
Labels: :bug: bug, :sparkles: feature, 성지순례, 마이페이지

#71 [FEAT #70] 비밀번호 재설정 로직 구현
  src/main/java/com/favoriteplace/app/controller/MemberController.java
  src/main/java/com/favoriteplace/app/domain/Member.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/global/security/service/CustomUserDetailsService.java
Labels: :sparkles: feature, 로그인/회원가입

#73 [FIX #72] 성지순례 영어,일어 주소 추가
  src/main/java/com/favoriteplace/app/converter/PilgrimageConverter.java
  src/main/java/com/favoriteplace/app/domain/travel/Pilgrimage.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageDto.java
Labels: :bug: bug, 성지순례

#74 [FIX] 성지순례 필드 수정
  src/main/java/com/favoriteplace/app/converter/PilgrimageConverter.java
  src/main/java/com/favoriteplace/app/domain/travel/Pilgrimage.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageDto.java
Labels: :bug: bug, 성지순례

#76 [fix #75] 성지순례 상세 조회 권한 해제
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
Labels: :bug: bug, 성지순례

#77 fix/#75 성지순례 상세 조회 접근 권한 해제
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
Labels: :bug: bug, 성지순례

#78 [FEAT #65] 조회 최적화
  src/main/java/com/favoriteplace/app/controller/Empty.java
  src/main/java/com/favoriteplace/app/controller/GuestBookCommentController.java
  src/main/java/com/favoriteplace/app/controller/GuestBookController.java
  src/main/java/com/favoriteplace/app/controller/HomeController.java
  src/main/java/com/favoriteplace/app/controller/PostCommentController.java
  src/main/java/com/favoriteplace/app/controller/PostController.java
  src/main/java/com/favoriteplace/app/converter/CommentConverter.java
  src/main/java/com/favoriteplace/app/converter/GuestBookConverter.java
  src/main/java/com/favoriteplace/app/converter/PilgrimageConverter.java
  src/main/java/com/favoriteplace/app/converter/PostConverter.java
  src/main/java/com/favoriteplace/app/converter/TrendingPostConverter.java
  src/main/java/com/favoriteplace/app/dto/community/GuestBookResponseDto.java
  src/main/java/com/favoriteplace/app/dto/community/PostResponseDto.java
  src/main/java/com/favoriteplace/app/repository/CommentImplRepository.java
  src/main/java/com/favoriteplace/app/repository/CommentRepository.java
  src/main/java/com/favoriteplace/app/repository/GuestBookImplRepository.java
  src/main/java/com/favoriteplace/app/repository/GuestBookRepository.java
  src/main/java/com/favoriteplace/app/repository/PostImplRepository.java
  src/main/java/com/favoriteplace/app/repository/PostRepository.java
  src/main/java/com/favoriteplace/app/repository/VisitedPilgrimageRepository.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
  src/main/java/com/favoriteplace/app/service/RallyService.java
  src/main/java/com/favoriteplace/app/service/TotalPostService.java
  src/main/java/com/favoriteplace/app/service/community/CommentQueryService.java
  src/main/java/com/favoriteplace/app/service/community/CountCommentsService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookQueryService.java
  src/main/java/com/favoriteplace/app/service/community/PostCommandService.java
  src/main/java/com/favoriteplace/app/service/community/PostQueryService.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchGuestBookByContent.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchGuestBookByNickname.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchGuestBookByTitle.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchPostByContent.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchPostByNickname.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchPostByTitle.java
  src/main/java/com/favoriteplace/app/service/community/searchStrategy/SearchStrategy.java
  src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortGuestBookByLatestStrategy.java
  src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortGuestBookByLikedStrategy.java
  src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortPostByLatestStrategy.java
  src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortPostByLikedStrategy.java
  src/main/java/com/favoriteplace/app/service/community/sortStrategy/SortStrategy.java
  src/main/resources/studious-matrix-412103-04030f986b9b.yml
Labels: :recycle: refactor, 홈, 커뮤니티

#81 [FIX #80] 날짜 출력 형식 수정
  src/main/java/com/favoriteplace/global/util/DateTimeFormatUtils.java
Labels: :recycle: refactor, 커뮤니티

#90 [FEAT #89] 로그아웃 기능 구현 + 필터 속 예외처리
  src/main/java/com/favoriteplace/app/controller/MemberController.java
  src/main/java/com/favoriteplace/app/domain/Member.java
  src/main/java/com/favoriteplace/app/service/MemberService.java
  src/main/java/com/favoriteplace/global/exception/ErrorCode.java
  src/main/java/com/favoriteplace/global/security/Filter/ExceptionHandlerFilter.java
  src/main/java/com/favoriteplace/global/security/Filter/JwtAuthenticationFilter.java
  src/main/java/com/favoriteplace/global/security/config/SecurityConfig.java
  src/main/java/com/favoriteplace/global/security/provider/JwtTokenProvider.java
  src/main/java/com/favoriteplace/global/util/SecurityUtil.java
Labels: :sparkles: feature, 로그인/회원가입

#92 [FIX #91] 성지순례 인증하기 api 수정
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageDto.java
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
Labels: :bug: bug, 성지순례

#93 방문 인증 api 배포
  src/main/java/com/favoriteplace/InitDB.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageDto.java
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
Labels: :bug: bug, 성지순례

#94 [FIX #91] 성지순례 인증 api UTC 기준으로 확인하도록 변경
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
Labels: :bug: bug, 성지순례

#95 방문 인증 api 수정
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
Labels: :bug: bug, 성지순례

#96 [FIX#91] 서버시간 UTC 표준으로 변경
  src/main/java/com/favoriteplace/FavoritePlaceApplication.java
Labels: :bug: bug, 성지순례

#97 서버 시간 UTC 변경
  src/main/java/com/favoriteplace/FavoritePlaceApplication.java
Labels: :bug: bug, 성지순례

#98 [FIX #91] 어플리케이션 시간 변경
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
Labels: :bug: bug, 성지순례

#101 어플리케이션 시간 한국으로 설정
  src/main/java/com/favoriteplace/FavoritePlaceApplication.java
Labels: :bug: bug, 성지순례

#102 [Fix/#91] 홈 api 수정, out of index 해결
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
  src/main/java/com/favoriteplace/app/service/RallyService.java
Labels: :bug: bug, 성지순례

#104 [FIX #91] complete rally JPA 수정
  src/main/java/com/favoriteplace/app/repository/CompleteRallyRepository.java
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
Labels: :bug: bug, 성지순례
