Repository UMC5th-bias/MoeMoe-Server, pull requests merged in 2024-12, with the labels that each got.

#159 [DEPLOY] main <- develop 병합
  build.gradle
  logs/logfile.log
  src/main/java/com/favoriteplace/app/controller/GuestBookCommentController.java
  src/main/java/com/favoriteplace/app/controller/GuestBookController.java
  src/main/java/com/favoriteplace/app/controller/MyPageController.java
  src/main/java/com/favoriteplace/app/controller/NotificationController.java
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/controller/PostCommentController.java
  src/main/java/com/favoriteplace/app/controller/PostController.java
  src/main/java/com/favoriteplace/app/domain/community/GuestBook.java
  src/main/java/com/favoriteplace/app/dto/community/PostResponseDto.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
  src/main/java/com/favoriteplace/app/service/community/LikedPostService.java
  src/main/java/com/favoriteplace/global/security/filter/ExceptionHandlerFilter.java
  src/main/java/com/favoriteplace/global/security/handler/CustomAuthenticationFailHandler.java
  src/main/resources/log4j2-develop.xml
  src/main/resources/log4j2.xml
Labels: 🔆 deploy

#161 [FEAT #157] nginx 무중단 배포 설정
  appspec.yml
  build.gradle
  src/main/java/com/favoriteplace/global/HelloController.java
Labels: :sparkles: feature, 🦋정윤

#162 [DEPLOY] main <- develop 병합
  appspec.yml
  build.gradle
  src/main/java/com/favoriteplace/global/HelloController.java
Labels: 🔆 deploy

#166 [REFACTOR] DTO record 타입으로 마이그레이션
  src/main/java/com/favoriteplace/app/controller/GuestBookCommentController.java
  src/main/java/com/favoriteplace/app/controller/GuestBookController.java
  src/main/java/com/favoriteplace/app/controller/PilgrimageApiController.java
  src/main/java/com/favoriteplace/app/controller/PilgrimageSocketController.java
  src/main/java/com/favoriteplace/app/controller/PostCommentController.java
  src/main/java/com/favoriteplace/app/converter/CommentConverter.java
  src/main/java/com/favoriteplace/app/converter/GuestBookConverter.java
  src/main/java/com/favoriteplace/app/converter/PilgrimageConverter.java
  src/main/java/com/favoriteplace/app/converter/RallyConverter.java
  src/main/java/com/favoriteplace/app/domain/travel/VisitedPilgrimage.java
  src/main/java/com/favoriteplace/app/dto/community/CommentRequestDto.java
  src/main/java/com/favoriteplace/app/dto/community/CommentResponseDto.java
  src/main/java/com/favoriteplace/app/dto/community/GuestBookRequestDto.java
  src/main/java/com/favoriteplace/app/dto/community/PostRequestDto.java
  src/main/java/com/favoriteplace/app/dto/community/comment/CommentCreateRequestDto.java
  src/main/java/com/favoriteplace/app/dto/community/comment/CommentModifyRequestDto.java
  src/main/java/com/favoriteplace/app/dto/community/comment/CommentParentResponseDto.java
  src/main/java/com/favoriteplace/app/dto/community/comment/CommentRootResponseDto.java
  src/main/java/com/favoriteplace/app/dto/community/comment/CommentSubResponseDto.java
  src/main/java/com/favoriteplace/app/dto/community/guestbook/GuestBookModifyRequestDto.java
  src/main/java/com/favoriteplace/app/dto/community/guestbook/GuestBookResponseDto.java
  src/main/java/com/favoriteplace/app/dto/item/Empty.java
  src/main/java/com/favoriteplace/app/dto/member/MemberDto.java
  src/main/java/com/favoriteplace/app/dto/travel/Empty.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageCertifyRequestDto.java
  src/main/java/com/favoriteplace/app/dto/travel/PilgrimageResponseDto.java
  src/main/java/com/favoriteplace/app/dto/travel/RallyResponseDto.java
  src/main/java/com/favoriteplace/app/service/PilgrimageCommandService.java
  src/main/java/com/favoriteplace/app/service/PilgrimageQueryService.java
  src/main/java/com/favoriteplace/app/service/community/CommentCommandService.java
  src/main/java/com/favoriteplace/app/service/community/CommentQueryService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookCommandService.java
  src/main/java/com/favoriteplace/app/service/community/GuestBookQueryService.java
  src/main/java/com/favoriteplace/app/service/community/PostCommandService.java
Labels: :recycle: refactor, 🐰수빈
